# Site settings
title: Giuseppe Gagliano
email: giuseppe.gagliano.antonio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: gacgagliano
github_username: giuseppegagliano
stackoverflow: ggagliano
linkedin: ggagliano

# Build settings
markdown: kramdown
